import React, { useState } from 'react';
import { Mic, FileAudio, Edit, FileSearch, AlertCircle, Zap, Video, MapPin, Radio, Code, Upload, Send, Loader2 } from 'lucide-react';

const AITools = () => {
  const [activeTab, setActiveTab] = useState<'voice' | 'legal' | 'image' | 'hashtag' | 'tv' | 'heatmap'>('voice');
  const [transcript, setTranscript] = useState('');
  const [notice, setNotice] = useState('');
  const [imageResult, setImageResult] = useState('');
  const [hashtagResult, setHashtagResult] = useState('');

  const mockProcess = (setter: (val: string) => void, label: string) => {
    setter('Processing...');
    setTimeout(() => {
      setter(`${label} generated by AI (mock data)`);
    }, 1500);
  };

  return (
    <div className="fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '2rem', height: '100%' }}>
      {/* Tabs */}
      <div style={{ display: 'flex', gap: '0.5rem', borderBottom: '1px solid var(--border-color)', paddingBottom: '8px' }}>
        <button onClick={() => setActiveTab('voice')} style={{
          background: 'transparent', border: 'none', color: activeTab === 'voice' ? '#8b5cf6' : 'var(--text-secondary)',
          fontSize: '1rem', fontWeight: 'bold', cursor: 'pointer', padding: '6px 12px',
          borderBottom: activeTab === 'voice' ? '2px solid #8b5cf6' : '2px solid transparent',
          display: 'flex', alignItems: 'center', gap: '6px'
        }}>
          <Mic size={18} /> Voice‑to‑Text
        </button>
        <button onClick={() => setActiveTab('legal')} style={{
          background: 'transparent', border: 'none', color: activeTab === 'legal' ? '#8b5cf6' : 'var(--text-secondary)',
          fontSize: '1rem', fontWeight: 'bold', cursor: 'pointer', padding: '6px 12px',
          borderBottom: activeTab === 'legal' ? '2px solid #8b5cf6' : '2px solid transparent',
          display: 'flex', alignItems: 'center', gap: '6px'
        }}>
          <Edit size={18} /> Legal Notice
        </button>
        <button onClick={() => setActiveTab('image')} style={{
          background: 'transparent', border: 'none', color: activeTab === 'image' ? '#8b5cf6' : 'var(--text-secondary)',
          fontSize: '1rem', fontWeight: 'bold', cursor: 'pointer', padding: '6px 12px',
          borderBottom: activeTab === 'image' ? '2px solid #8b5cf6' : '2px solid transparent',
          display: 'flex', alignItems: 'center', gap: '6px'
        }}>
          <FileSearch size={18} /> Reverse Image
        </button>
        <button onClick={() => setActiveTab('hashtag')} style={{
          background: 'transparent', border: 'none', color: activeTab === 'hashtag' ? '#8b5cf6' : 'var(--text-secondary)',
          fontSize: '1rem', fontWeight: 'bold', cursor: 'pointer', padding: '6px 12px',
          borderBottom: activeTab === 'hashtag' ? '2px solid #8b5cf6' : '2px solid transparent',
          display: 'flex', alignItems: 'center', gap: '6px'
        }}>
          <Zap size={18} /> Hashtag Guard
        </button>
        <button onClick={() => setActiveTab('tv')} style={{
          background: 'transparent', border: 'none', color: activeTab === 'tv' ? '#8b5cf6' : 'var(--text-secondary)',
          fontSize: '1rem', fontWeight: 'bold', cursor: 'pointer', padding: '6px 12px',
          borderBottom: activeTab === 'tv' ? '2px solid #8b5cf6' : '2px solid transparent',
          display: 'flex', alignItems: 'center', gap: '6px'
        }}>
          <Video size={18} /> TV Live Feed
        </button>
        <button onClick={() => setActiveTab('heatmap')} style={{
          background: 'transparent', border: 'none', color: activeTab === 'heatmap' ? '#8b5cf6' : 'var(--text-secondary)',
          fontSize: '1rem', fontWeight: 'bold', cursor: 'pointer', padding: '6px 12px',
          borderBottom: activeTab === 'heatmap' ? '2px solid #8b5cf6' : '2px solid transparent',
          display: 'flex', alignItems: 'center', gap: '6px'
        }}>
          <MapPin size={18} /> Sentiment Heatmap
        </button>
      </div>

      {/* Content Panels */}
      {activeTab === 'voice' && (
        <div className="glass-panel" style={{ padding: '1.5rem', flex: 1 }}>
          <h3 className="section-title">Voice‑to‑Text Analytics</h3>
          <p style={{ color: 'var(--text-secondary)' }}>Upload an audio or video clip (local language) to get an instant transcription. Keywords are highlighted for quick hate‑speech detection.</p>
          <div style={{ marginTop: '1rem' }}>
            <input type="file" accept="audio/*,video/*" style={{ color: 'var(--text-primary)' }} />
            <button onClick={() => mockProcess(setTranscript, 'Transcribed text')} style={{
              marginLeft: '8px', background: '#8b5cf6', color: 'white', border: 'none', padding: '6px 12px', borderRadius: '4px', cursor: 'pointer'
            }}>
              <Mic size={16} /> Transcribe
            </button>
          </div>
          <textarea readOnly value={transcript} placeholder="Transcription will appear here..."
            style={{ width: '100%', minHeight: '180px', marginTop: '1rem', background: 'rgba(0,0,0,0.2)', color: 'white', border: '1px solid var(--border-color)', borderRadius: '4px', padding: '10px' }} />
        </div>
      )}

      {activeTab === 'legal' && (
        <div className="glass-panel" style={{ padding: '1.5rem', flex: 1 }}>
          <h3 className="section-title">Automated IT‑Act Notice Generator</h3>
          <p style={{ color: 'var(--text-secondary)' }}>Enter the offending handle or URL; the system will craft a legal notice under IT Act Sec 66/69.</p>
          <div style={{ display: 'flex', gap: '1rem', marginTop: '1rem' }}>
            <input type="text" placeholder="@offending_handle or URL" style={{ flex: 1, padding: '6px', background: 'rgba(0,0,0,0.2)', color: 'white', border: '1px solid var(--border-color)', borderRadius: '4px' }} />
            <button onClick={() => mockProcess(setNotice, 'Legal Notice')} style={{ background: '#8b5cf6', color: 'white', border: 'none', padding: '6px 12px', borderRadius: '4px', cursor: 'pointer' }}>
              <Edit size={16} /> Generate
            </button>
          </div>
          <textarea readOnly value={notice} placeholder="Generated notice appears here..."
            style={{ width: '100%', minHeight: '180px', marginTop: '1rem', background: 'rgba(0,0,0,0.2)', color: 'white', border: '1px solid var(--border-color)', borderRadius: '4px', padding: '10px' }} />
        </div>
      )}

      {activeTab === 'image' && (
        <div className="glass-panel" style={{ padding: '1.5rem', flex: 1 }}>
          <h3 className="section-title">Reverse Image Search</h3>
          <p style={{ color: 'var(--text-secondary)' }}>Upload a suspicious image – the tool checks the web for matches and shows provenance.</p>
          <div style={{ marginTop: '1rem' }}>
            <input type="file" accept="image/*" style={{ color: 'var(--text-primary)' }} />
            <button onClick={() => mockProcess(setImageResult, 'Image provenance')} style={{
              marginLeft: '8px', background: '#8b5cf6', color: 'white', border: 'none', padding: '6px 12px', borderRadius: '4px', cursor: 'pointer'
            }}>
              <FileSearch size={16} /> Search
            </button>
          </div>
          <div style={{ marginTop: '1rem', background: 'rgba(0,0,0,0.1)', padding: '1rem', borderRadius: '4px' }}>
            {imageResult || 'Result will appear here after processing.'}
          </div>
        </div>
      )}

      {activeTab === 'hashtag' && (
        <div className="glass-panel" style={{ padding: '1.5rem', flex: 1 }}>
          <h3 className="section-title">Hashtag Hijacking Control</h3>
          <p style={{ color: 'var(--text-secondary)' }}>Enter a trending hashtag that is being misused. The system suggests positive counter‑posts.</p>
          <div style={{ display: 'flex', gap: '1rem', marginTop: '1rem' }}>
            <input type="text" placeholder="#misusedHashtag" style={{ flex: 1, padding: '6px', background: 'rgba(0,0,0,0.2)', color: 'white', border: '1px solid var(--border-color)', borderRadius: '4px' }} />
            <button onClick={() => mockProcess(setHashtagResult, 'Counter‑posts')} style={{ background: '#8b5cf6', color: 'white', border: 'none', padding: '6px 12px', borderRadius: '4px', cursor: 'pointer' }}>
              <Zap size={16} /> Generate
            </button>
          </div>
          <div style={{ marginTop: '1rem', background: 'rgba(0,0,0,0.1)', padding: '1rem', borderRadius: '4px' }}>
            {hashtagResult || 'Suggested positive posts will appear here.'}
          </div>
        </div>
      )}

      {activeTab === 'tv' && (
        <div className="glass-panel" style={{ padding: '1.5rem', flex: 1, overflowY: 'auto' }}>
          <h3 className="section-title">TV News Live Monitoring</h3>
          <p style={{ color: 'var(--text-secondary)' }}>Live streams from regional news channels – any breaking news flashes in <strong>30 seconds</strong>.</p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '1rem', marginTop: '1rem' }}>
            {[1, 2, 3, 4].map(i => (
              <div key={i} style={{ background: 'rgba(0,0,0,0.3)', height: '180px', borderRadius: '4px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-secondary)' }}>
                TV Channel {i} (Live Stream Placeholder)
              </div>
            ))}
          </div>
        </div>
      )}

      {activeTab === 'heatmap' && (
        <div className="glass-panel" style={{ padding: '1.5rem', flex: 1 }}>
          <h3 className="section-title">Community Sentiment Heatmap</h3>
          <p style={{ color: 'var(--text-secondary)' }}>A map visualising sentiment intensity per locality. Red zones = high negative sentiment.</p>
          <div style={{ width: '100%', height: '400px', marginTop: '1rem', background: 'rgba(0,0,0,0.2)', borderRadius: '4px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-secondary)' }}>
            [Map Heatmap Placeholder – integrate with react‑leaflet for production]
          </div>
        </div>
      )}
    </div>
  );
};

export default AITools;
